spring.application.name=backend

# Server Settings
server.error.include-stacktrace=never

# API Settings
spring.mvc.contentnegotiation.favor-path-extension=false
spring.mvc.contentnegotiation.favor-parameter=false
spring.mvc.contentnegotiation.ignore-accept-header=false
spring.mvc.contentnegotiation.default-content-type=application/json

# API Responses
spring.jackson.default-property-inclusion=non_null

# MongoDB settings
spring.data.mongodb.host=mongo
spring.data.mongodb.port=27017
spring.data.mongodb.database=humpbackdb

# Security
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS}

# Sysadmin settings
sysadmin.username=${SYSADMIN_USERNAME}
sysadmin.username=${SYSADMIN_FULLNAME}
sysadmin.email=${SYSADMIN_EMAIL}
sysadmin.password=${SYSADMIN_PASSWORD}
